export const ActionTypes = {
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    DELETE_ITEM: "DELETE_ITEM",
    CHANGE_CART: "CHANGE_CART",
    FILTER_PRODUCTS: "FILTER_PRODUCTS"
}